### ISSUE TITLE
NBT tag

### ISSUE THREAD

**Issue by thecorpus2** [Bommels05/CrafttweakerGUI#1]
While a gui is an indispensable element to make CT useful and efficient and you are contributing greatly to the community making this mod, I am sorely missing the ability to add nbt tags to the output of recipes. This capability is very important and if only it could be put into regular crafting table crafting it would be tremendously useful.

**Comment by Bommels05** [comment]
You can already do this, you just need to have the Item with NBT in your hotbar and drag it into the output slot.
In 1.20.4 some mods like Mekanism use data attachments for items which crafttweaker itself doesn't support, so maybe that is actually the problem you have.
